"""empty message

Revision ID: 0550f734024d
Revises: f89b23cd2a7c
Create Date: 2021-06-11 22:27:28.968096

"""
from alembic import op
import sqlalchemy as sa
import lib
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0550f734024d'
down_revision = 'f89b23cd2a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spng_survey_camps', 'created_on')
    op.drop_column('spng_survey_camps', 'updated_on')
    op.drop_column('spng_survey_programs', 'created_on')
    op.drop_column('spng_survey_programs', 'updated_on')
    op.drop_column('spng_survey_teams', 'created_on')
    op.drop_column('spng_survey_teams', 'updated_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spng_survey_teams', sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    op.add_column('spng_survey_teams', sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    op.add_column('spng_survey_programs', sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    op.add_column('spng_survey_programs', sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    op.add_column('spng_survey_camps', sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    op.add_column('spng_survey_camps', sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
