"""empty message

Revision ID: 1a17c7ddcec7
Revises: 
Create Date: 2021-05-27 21:04:24.457889

"""
from alembic import op
import sqlalchemy as sa
import lib


# revision identifiers, used by Alembic.
revision = '1a17c7ddcec7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('program_groups', sa.Column('program_id', sa.Integer(), nullable=True))
	op.drop_constraint('program_groups_camp_id_fkey', 'program_groups', type_='foreignkey')
	op.create_foreign_key(None, 'program_groups', 'programs', ['program_id'], ['id'])
	op.drop_column('program_groups', 'camp_id')
	# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column('program_groups', sa.Column('camp_id', sa.INTEGER(), autoincrement=False, nullable=True))
	op.drop_constraint(None, 'program_groups', type_='foreignkey')
	op.create_foreign_key('program_groups_camp_id_fkey', 'program_groups', 'camps', ['camp_id'], ['id'])
	op.drop_column('program_groups', 'program_id')
	# ### end Alembic commands ###
