"""empty message

Revision ID: 33189738609c
Revises: a959aac18714
Create Date: 2021-06-16 17:33:47.394587

"""
from alembic import op
import sqlalchemy as sa
import lib
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33189738609c'
down_revision = 'a959aac18714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_categories',
    sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_live', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adult_reps',
    sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_adult_reps_full_name'), 'adult_reps', ['full_name'], unique=False)
    op.create_table('resources',
    sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_live', sa.Boolean(), server_default='1', nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('thumbnail_image_url', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['resource_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_table('resource_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_body', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_pdfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_instances_adult_reps',
    sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('team_instance_id', sa.Integer(), nullable=False),
    sa.Column('adult_rep_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['adult_rep_id'], ['adult_reps.id'], ),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.PrimaryKeyConstraint('team_instance_id', 'adult_rep_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_instances_adult_reps')
    op.drop_table('resource_videos')
    op.drop_table('resource_pdfs')
    op.drop_table('resource_articles')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_adult_reps_full_name'), table_name='adult_reps')
    op.drop_table('adult_reps')
    op.drop_table('resource_categories')
    # ### end Alembic commands ###
