"""empty message

Revision ID: 3403621c91b3
Revises: e31eefe218c0
Create Date: 2021-05-29 18:35:17.951649

"""
from alembic import op
import sqlalchemy as sa
import lib


# revision identifiers, used by Alembic.
revision = '3403621c91b3'
down_revision = 'e31eefe218c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians_players', sa.Column('is_emergency_contact', sa.Boolean(), nullable=True))
    op.drop_column('guardians_players', 'is_emergency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians_players', sa.Column('is_emergency', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('guardians_players', 'is_emergency_contact')
    # ### end Alembic commands ###
