"""empty message

Revision ID: 4dcec7de5747
Revises: 32bf163d6e95
Create Date: 2021-07-19 10:48:41.499609

"""
from alembic import op
import sqlalchemy as sa
import main.utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4dcec7de5747'
down_revision = '32bf163d6e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camp_instance_registrations', sa.Column('owes', sa.Float(), nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('paid', sa.Float(), nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('total', sa.Float(), nullable=True))
    op.drop_column('camp_instance_registrations', 'service_fee_forecast')
    op.drop_column('camp_instance_registrations', 'net_forecast')
    op.drop_column('camp_instance_registrations', 'net')
    op.drop_column('camp_instance_registrations', 'service_fee')
    op.drop_column('camp_instance_registrations', 'gross_forecast')
    op.drop_column('camp_instance_registrations', 'gross_outstanding')
    op.drop_column('camp_instance_registrations', 'gross')
    op.add_column('program_instance_registrations', sa.Column('owes', sa.Float(), nullable=True))
    op.add_column('program_instance_registrations', sa.Column('paid', sa.Float(), nullable=True))
    op.add_column('program_instance_registrations', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('program_instance_registrations', sa.Column('total', sa.Float(), nullable=True))
    op.drop_column('program_instance_registrations', 'service_fee_forecast')
    op.drop_column('program_instance_registrations', 'net_forecast')
    op.drop_column('program_instance_registrations', 'net')
    op.drop_column('program_instance_registrations', 'service_fee')
    op.drop_column('program_instance_registrations', 'gross_forecast')
    op.drop_column('program_instance_registrations', 'gross_outstanding')
    op.drop_column('program_instance_registrations', 'gross')
    op.add_column('team_instance_registrations', sa.Column('owes', sa.Float(), nullable=True))
    op.add_column('team_instance_registrations', sa.Column('paid', sa.Float(), nullable=True))
    op.add_column('team_instance_registrations', sa.Column('refund_reason', sa.Text(), nullable=True))
    op.add_column('team_instance_registrations', sa.Column('total', sa.Float(), nullable=True))
    op.drop_column('team_instance_registrations', 'service_fee_forecast')
    op.drop_column('team_instance_registrations', 'net_forecast')
    op.drop_column('team_instance_registrations', 'net')
    op.drop_column('team_instance_registrations', 'service_fee')
    op.drop_column('team_instance_registrations', 'gross_forecast')
    op.drop_column('team_instance_registrations', 'gross_outstanding')
    op.drop_column('team_instance_registrations', 'gross')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_instance_registrations', sa.Column('gross', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_instance_registrations', sa.Column('gross_outstanding', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_instance_registrations', sa.Column('gross_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_instance_registrations', sa.Column('service_fee', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_instance_registrations', sa.Column('net', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_instance_registrations', sa.Column('net_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_instance_registrations', sa.Column('service_fee_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('team_instance_registrations', 'total')
    op.drop_column('team_instance_registrations', 'refund_reason')
    op.drop_column('team_instance_registrations', 'paid')
    op.drop_column('team_instance_registrations', 'owes')
    op.add_column('program_instance_registrations', sa.Column('gross', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('program_instance_registrations', sa.Column('gross_outstanding', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('program_instance_registrations', sa.Column('gross_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('program_instance_registrations', sa.Column('service_fee', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('program_instance_registrations', sa.Column('net', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('program_instance_registrations', sa.Column('net_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('program_instance_registrations', sa.Column('service_fee_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('program_instance_registrations', 'total')
    op.drop_column('program_instance_registrations', 'refund_reason')
    op.drop_column('program_instance_registrations', 'paid')
    op.drop_column('program_instance_registrations', 'owes')
    op.add_column('camp_instance_registrations', sa.Column('gross', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('gross_outstanding', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('gross_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('service_fee', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('net', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('net_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('service_fee_forecast', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('camp_instance_registrations', 'total')
    op.drop_column('camp_instance_registrations', 'refund_reason')
    op.drop_column('camp_instance_registrations', 'paid')
    op.drop_column('camp_instance_registrations', 'owes')
    # ### end Alembic commands ###
