"""empty message

Revision ID: 5453c962223e
Revises: 89855199d7f9
Create Date: 2021-08-09 14:15:51.351789

"""
from alembic import op
import sqlalchemy as sa
import main.utils


# revision identifiers, used by Alembic.
revision = '5453c962223e'
down_revision = '89855199d7f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camp_instance_registrations', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('camp_instance_registrations', sa.Column('jersey_size', sa.String(), nullable=True))
    op.add_column('program_instance_registrations', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('program_instance_registrations', sa.Column('jersey_size', sa.String(), nullable=True))
    op.add_column('team_instance_registrations', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('team_instance_registrations', sa.Column('jersey_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_instance_registrations', 'jersey_size')
    op.drop_column('team_instance_registrations', 'jersey_number')
    op.drop_column('program_instance_registrations', 'jersey_size')
    op.drop_column('program_instance_registrations', 'jersey_number')
    op.drop_column('camp_instance_registrations', 'jersey_size')
    op.drop_column('camp_instance_registrations', 'jersey_number')
    # ### end Alembic commands ###
