"""empty message

Revision ID: 589d7d063589
Revises: 879925dce74d
Create Date: 2021-06-22 10:01:06.971445

"""
from alembic import op
import sqlalchemy as sa
import lib
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '589d7d063589'
down_revision = '879925dce74d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('is_live', sa.Boolean(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forms', 'is_live')
    # ### end Alembic commands ###
