"""empty message

Revision ID: 5f8c3f48824e
Revises: fb05c65555c9
Create Date: 2021-08-24 11:31:44.058340

"""
from alembic import op
import sqlalchemy as sa
import main.utils


# revision identifiers, used by Alembic.
revision = '5f8c3f48824e'
down_revision = 'fb05c65555c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_instance_jersey_socks_order_updates', sa.Column('old_jersey_number', sa.Integer(), nullable=True))
    op.add_column('team_instance_jersey_socks_order_updates', sa.Column('old_jersey_size', sa.String(), nullable=True))
    op.add_column('team_instance_jersey_socks_order_updates', sa.Column('old_player_full_name', sa.String(), nullable=True))
    op.add_column('team_instance_jersey_socks_order_updates', sa.Column('old_socks_size', sa.String(), nullable=True))
    op.add_column('team_instance_jersey_sponsor_order_updates', sa.Column('old_amount', sa.Float(), nullable=True))
    op.add_column('team_instance_jersey_sponsor_order_updates', sa.Column('old_name', sa.String(), nullable=True))
    op.add_column('team_instance_jersey_sponsor_order_updates', sa.Column('old_player_full_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_team_instance_jersey_sponsor_order_updates_old_name'), 'team_instance_jersey_sponsor_order_updates', ['old_name'], unique=False)
    op.create_index(op.f('ix_team_instance_jersey_sponsor_order_updates_old_player_full_name'), 'team_instance_jersey_sponsor_order_updates', ['old_player_full_name'], unique=False)
    op.add_column('team_instance_tracksuit_order_updates', sa.Column('old_coach_full_name', sa.String(length=120), nullable=True))
    op.add_column('team_instance_tracksuit_order_updates', sa.Column('old_jacket_size', sa.String(length=50), nullable=True))
    op.add_column('team_instance_tracksuit_order_updates', sa.Column('old_pants_size', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_instance_tracksuit_order_updates', 'old_pants_size')
    op.drop_column('team_instance_tracksuit_order_updates', 'old_jacket_size')
    op.drop_column('team_instance_tracksuit_order_updates', 'old_coach_full_name')
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_order_updates_old_player_full_name'), table_name='team_instance_jersey_sponsor_order_updates')
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_order_updates_old_name'), table_name='team_instance_jersey_sponsor_order_updates')
    op.drop_column('team_instance_jersey_sponsor_order_updates', 'old_player_full_name')
    op.drop_column('team_instance_jersey_sponsor_order_updates', 'old_name')
    op.drop_column('team_instance_jersey_sponsor_order_updates', 'old_amount')
    op.drop_column('team_instance_jersey_socks_order_updates', 'old_socks_size')
    op.drop_column('team_instance_jersey_socks_order_updates', 'old_player_full_name')
    op.drop_column('team_instance_jersey_socks_order_updates', 'old_jersey_size')
    op.drop_column('team_instance_jersey_socks_order_updates', 'old_jersey_number')
    # ### end Alembic commands ###
