"""empty message

Revision ID: 5f8ee52b4320
Revises: ad884bea3de8
Create Date: 2021-07-22 17:01:52.944778

"""
from alembic import op
import sqlalchemy as sa
import main.utils


# revision identifiers, used by Alembic.
revision = '5f8ee52b4320'
down_revision = 'ad884bea3de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_instance_jersey_socks_order_group_sheets',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('team_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_instance_tracksuit_order_group_sheets',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('team_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_instance_tracksuit_order_requests',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_instance_id', sa.Integer(), nullable=True),
    sa.Column('team_instance_tracksuit_order_id', sa.Integer(), nullable=True),
    sa.Column('jacket_size', sa.String(length=50), nullable=True),
    sa.Column('pants_size', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.ForeignKeyConstraint(['team_instance_tracksuit_order_id'], ['team_instance_tracksuit_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_instance_tracksuit_order_updates',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_instance_tracksuit_order_id', sa.Integer(), nullable=True),
    sa.Column('new_coach_full_name', sa.String(length=120), nullable=True),
    sa.Column('new_jacket_size', sa.String(length=50), nullable=True),
    sa.Column('new_pants_size', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_tracksuit_order_id'], ['team_instance_tracksuit_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_instance_jersey_socks_order_requests',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_instance_id', sa.Integer(), nullable=True),
    sa.Column('team_instance_registration_id', sa.Integer(), nullable=True),
    sa.Column('team_instance_jersey_socks_order_id', sa.Integer(), nullable=True),
    sa.Column('player_full_name', sa.String(), nullable=True),
    sa.Column('jersey_number', sa.Integer(), nullable=True),
    sa.Column('jersey_size', sa.String(), nullable=True),
    sa.Column('socks_size', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.ForeignKeyConstraint(['team_instance_jersey_socks_order_id'], ['team_instance_jersey_socks_orders.id'], ),
    sa.ForeignKeyConstraint(['team_instance_registration_id'], ['team_instance_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_instance_jersey_socks_order_updates',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_instance_jersey_socks_order_id', sa.Integer(), nullable=True),
    sa.Column('new_player_full_name', sa.String(), nullable=True),
    sa.Column('new_jersey_number', sa.Integer(), nullable=True),
    sa.Column('new_jersey_size', sa.String(), nullable=True),
    sa.Column('new_socks_size', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_jersey_socks_order_id'], ['team_instance_jersey_socks_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('team_instance_jersey_socks_orders', sa.Column('player_full_name', sa.String(), nullable=True))
    op.add_column('team_instance_tracksuit_orders', sa.Column('coach_full_name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_instance_tracksuit_orders', 'coach_full_name')
    op.drop_column('team_instance_jersey_socks_orders', 'player_full_name')
    op.drop_table('team_instance_jersey_socks_order_updates')
    op.drop_table('team_instance_jersey_socks_order_requests')
    op.drop_table('team_instance_tracksuit_order_updates')
    op.drop_table('team_instance_tracksuit_order_requests')
    op.drop_table('team_instance_tracksuit_order_group_sheets')
    op.drop_table('team_instance_jersey_socks_order_group_sheets')
    # ### end Alembic commands ###
