"""empty message

Revision ID: 6df81505bf5c
Revises: 7d890f764c48
Create Date: 2021-05-27 22:35:00.386468

"""
from alembic import op
import sqlalchemy as sa
import lib


# revision identifiers, used by Alembic.
revision = '6df81505bf5c'
down_revision = '7d890f764c48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_instance_jersey_socks_orders', sa.Column('jersey_number', sa.Integer(), nullable=True))
    op.add_column('team_instance_jersey_socks_orders', sa.Column('jersey_size', sa.String(), nullable=True))
    op.add_column('team_instance_jersey_socks_orders', sa.Column('socks_size', sa.String(), nullable=True))
    op.add_column('team_instance_tracksuit_orders', sa.Column('jacket_size', sa.String(length=50), nullable=True))
    op.add_column('team_instance_tracksuit_orders', sa.Column('pants_size', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_instance_tracksuit_orders', 'pants_size')
    op.drop_column('team_instance_tracksuit_orders', 'jacket_size')
    op.drop_column('team_instance_jersey_socks_orders', 'socks_size')
    op.drop_column('team_instance_jersey_socks_orders', 'jersey_size')
    op.drop_column('team_instance_jersey_socks_orders', 'jersey_number')
    # ### end Alembic commands ###
