"""empty message

Revision ID: 7d890f764c48
Revises: 1a17c7ddcec7
Create Date: 2021-05-27 21:22:28.791806

"""
from alembic import op
import sqlalchemy as sa
import lib


# revision identifiers, used by Alembic.
revision = '7d890f764c48'
down_revision = '1a17c7ddcec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guardians', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'guardians', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'guardians', type_='foreignkey')
    op.drop_column('guardians', 'user_id')
    # ### end Alembic commands ###
