"""empty message

Revision ID: 879925dce74d
Revises: 33189738609c
Create Date: 2021-06-17 16:50:43.518095

"""
from alembic import op
import sqlalchemy as sa
import lib
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '879925dce74d'
down_revision = '33189738609c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_entries', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_form_entries_slug'), 'form_entries', ['slug'], unique=True)
    op.add_column('forms', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_column('forms', 'slug')
    op.drop_index(op.f('ix_form_entries_slug'), table_name='form_entries')
    op.drop_column('form_entries', 'slug')
    # ### end Alembic commands ###
