"""empty message

Revision ID: 89855199d7f9
Revises: 91b60088371c
Create Date: 2021-08-08 21:49:24.898851

"""
from alembic import op
import sqlalchemy as sa
import main.utils


# revision identifiers, used by Alembic.
revision = '89855199d7f9'
down_revision = '91b60088371c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camp_instance_registrations', sa.Column('spng_order_number', sa.String(), nullable=True))
    op.drop_column('camp_instance_registrations', 'order_number')
    op.add_column('program_instance_registrations', sa.Column('spng_order_number', sa.String(), nullable=True))
    op.drop_column('program_instance_registrations', 'order_number')
    op.add_column('team_instance_registrations', sa.Column('spng_order_number', sa.String(), nullable=True))
    op.drop_column('team_instance_registrations', 'order_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_instance_registrations', sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('team_instance_registrations', 'spng_order_number')
    op.add_column('program_instance_registrations', sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('program_instance_registrations', 'spng_order_number')
    op.add_column('camp_instance_registrations', sa.Column('order_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('camp_instance_registrations', 'spng_order_number')
    # ### end Alembic commands ###
