"""empty message

Revision ID: a959aac18714
Revises: f89b23cd2a7c
Create Date: 2021-06-12 10:08:14.094156

"""
from alembic import op
import sqlalchemy as sa
import lib
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a959aac18714'
down_revision = 'f89b23cd2a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spng_meta', sa.Column('last_fetched_registrations', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spng_meta', 'last_fetched_registrations')
    # ### end Alembic commands ###
