"""empty message

Revision ID: ba9222e52ac8
Revises: 80d5272c7bf9
Create Date: 2021-07-30 11:21:30.864655

"""
from alembic import op
import sqlalchemy as sa
import main.utils


# revision identifiers, used by Alembic.
revision = 'ba9222e52ac8'
down_revision = '80d5272c7bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camp_instances_coaches', sa.Column('is_parent_coach', sa.Boolean(), nullable=True))
    op.add_column('program_instances_coaches', sa.Column('is_parent_coach', sa.Boolean(), nullable=True))
    op.add_column('team_instances_coaches', sa.Column('is_parent_coach', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_instances_coaches', 'is_parent_coach')
    op.drop_column('program_instances_coaches', 'is_parent_coach')
    op.drop_column('camp_instances_coaches', 'is_parent_coach')
    # ### end Alembic commands ###
