"""empty message

Revision ID: be3e7d3f03ea
Revises: 
Create Date: 2021-05-31 17:24:42.303011

"""
from alembic import op
import sqlalchemy as sa
import lib


# revision identifiers, used by Alembic.
revision = 'be3e7d3f03ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('player_id', sa.Integer(), nullable=True))
    op.create_foreign_key('registrations_player_id', 'registrations', 'players', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registrations_player_id', 'registrations', type_='foreignkey')
    op.drop_column('registrations', 'player_id')
    # ### end Alembic commands ###
