"""empty message

Revision ID: e5254e9bea1d
Revises: e803b278fe52
Create Date: 2021-08-25 16:46:16.240118

"""
from alembic import op
import sqlalchemy as sa
import main.utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5254e9bea1d'
down_revision = 'e803b278fe52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_index('ix_users_role', table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
