"""empty message

Revision ID: e803b278fe52
Revises: 5f8c3f48824e
Create Date: 2021-08-24 11:58:28.650348

"""
from alembic import op
import sqlalchemy as sa
import main.utils


# revision identifiers, used by Alembic.
revision = 'e803b278fe52'
down_revision = '5f8c3f48824e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_instance_jersey_sponsor_orders', sa.Column('player_full_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_team_instance_jersey_sponsor_orders_player_full_name'), 'team_instance_jersey_sponsor_orders', ['player_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_orders_player_full_name'), table_name='team_instance_jersey_sponsor_orders')
    op.drop_column('team_instance_jersey_sponsor_orders', 'player_full_name')
    # ### end Alembic commands ###
