"""empty message

Revision ID: f89b23cd2a7c
Revises: 1c001863701f
Create Date: 2021-06-11 21:40:39.018309

"""
from alembic import op
import sqlalchemy as sa
import lib
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f89b23cd2a7c'
down_revision = '1c001863701f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spng_survey_camps', sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    op.add_column('spng_survey_camps', sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    op.add_column('spng_survey_programs', sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    op.add_column('spng_survey_programs', sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    op.add_column('spng_survey_teams', sa.Column('created_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    op.add_column('spng_survey_teams', sa.Column('updated_on', lib.util_sqlalchemy.AwareDateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spng_survey_teams', 'updated_on')
    op.drop_column('spng_survey_teams', 'created_on')
    op.drop_column('spng_survey_programs', 'updated_on')
    op.drop_column('spng_survey_programs', 'created_on')
    op.drop_column('spng_survey_camps', 'updated_on')
    op.drop_column('spng_survey_camps', 'created_on')
    # ### end Alembic commands ###
