"""empty message

Revision ID: fb05c65555c9
Revises: ad268baab9dc
Create Date: 2021-08-24 09:54:06.997578

"""
from alembic import op
import sqlalchemy as sa
import main.utils
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb05c65555c9'
down_revision = 'ad268baab9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_instance_jersey_sponsor_order_group_sheets',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('team_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_instance_jersey_sponsor_orders',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_instance_id', sa.Integer(), nullable=True),
    sa.Column('team_instance_registration_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.ForeignKeyConstraint(['team_instance_registration_id'], ['team_instance_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_instance_jersey_sponsor_orders_name'), 'team_instance_jersey_sponsor_orders', ['name'], unique=False)
    op.create_table('team_instance_jersey_sponsor_order_requests',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_instance_id', sa.Integer(), nullable=True),
    sa.Column('team_instance_registration_id', sa.Integer(), nullable=True),
    sa.Column('team_instance_jersey_sponsor_order_id', sa.Integer(), nullable=True),
    sa.Column('player_full_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.Column('rejected_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_id'], ['team_instances.id'], ),
    sa.ForeignKeyConstraint(['team_instance_jersey_sponsor_order_id'], ['team_instance_jersey_sponsor_orders.id'], ),
    sa.ForeignKeyConstraint(['team_instance_registration_id'], ['team_instance_registrations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_instance_jersey_sponsor_order_requests_name'), 'team_instance_jersey_sponsor_order_requests', ['name'], unique=False)
    op.create_index(op.f('ix_team_instance_jersey_sponsor_order_requests_player_full_name'), 'team_instance_jersey_sponsor_order_requests', ['player_full_name'], unique=False)
    op.create_table('team_instance_jersey_sponsor_order_updates',
    sa.Column('created_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('updated_on', main.utils.sqlalchemy.AwareDateTime(), server_default=sa.text("timezone('utc'::text, now())"), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_instance_jersey_sponsor_order_id', sa.Integer(), nullable=True),
    sa.Column('new_player_full_name', sa.String(), nullable=True),
    sa.Column('new_name', sa.String(), nullable=True),
    sa.Column('new_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_instance_jersey_sponsor_order_id'], ['team_instance_jersey_sponsor_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_instance_jersey_sponsor_order_updates_new_name'), 'team_instance_jersey_sponsor_order_updates', ['new_name'], unique=False)
    op.create_index(op.f('ix_team_instance_jersey_sponsor_order_updates_new_player_full_name'), 'team_instance_jersey_sponsor_order_updates', ['new_player_full_name'], unique=False)
    op.drop_index('ix_team_instance_registration_jersey_sponsors_name', table_name='team_instance_registration_jersey_sponsors')
    op.drop_table('team_instance_registration_jersey_sponsors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_instance_registration_jersey_sponsors',
    sa.Column('created_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('updated_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_instance_registration_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_instance_registration_id'], ['team_instance_registrations.id'], name='team_instance_registration_je_team_instance_registration_i_fkey'),
    sa.PrimaryKeyConstraint('id', name='team_instance_registration_jersey_sponsors_pkey')
    )
    op.create_index('ix_team_instance_registration_jersey_sponsors_name', 'team_instance_registration_jersey_sponsors', ['name'], unique=False)
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_order_updates_new_player_full_name'), table_name='team_instance_jersey_sponsor_order_updates')
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_order_updates_new_name'), table_name='team_instance_jersey_sponsor_order_updates')
    op.drop_table('team_instance_jersey_sponsor_order_updates')
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_order_requests_player_full_name'), table_name='team_instance_jersey_sponsor_order_requests')
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_order_requests_name'), table_name='team_instance_jersey_sponsor_order_requests')
    op.drop_table('team_instance_jersey_sponsor_order_requests')
    op.drop_index(op.f('ix_team_instance_jersey_sponsor_orders_name'), table_name='team_instance_jersey_sponsor_orders')
    op.drop_table('team_instance_jersey_sponsor_orders')
    op.drop_table('team_instance_jersey_sponsor_order_group_sheets')
    # ### end Alembic commands ###
